# Generated by Django 4.0.2 on 2023-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
